# Generated by Django 4.2.11 on 2024-09-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_barterorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='current_account',
            new_name='current_amount',
        ),
    ]
